    mytree->SetBranchStatus("*",0);
    mytree->SetBranchStatus("run",1);
    mytree->SetBranchAddress("run", & run);
    mytree->SetBranchStatus("evt",1);
    mytree->SetBranchAddress("evt", & evt);
    mytree->SetBranchStatus("nJet30",1);
    mytree->SetBranchAddress("nJet30", & nJet30);
    mytree->SetBranchStatus("nJet50",1);
    mytree->SetBranchAddress("nJet50", & nJet50);
    mytree->SetBranchStatus("nBtag_loose",1);
    mytree->SetBranchAddress("nBtag_loose", & nBtag_loose);
    mytree->SetBranchStatus("nBtag_medium",1);
    mytree->SetBranchAddress("nBtag_medium", & nBtag_medium);
    mytree->SetBranchStatus("nBtag_tight",1);
    mytree->SetBranchAddress("nBtag_tight", & nBtag_tight);
    mytree->SetBranchStatus("nPV",1);
    mytree->SetBranchAddress("nPV", & nPV);
    mytree->SetBranchStatus("nPU_mean",1);
    mytree->SetBranchAddress("nPU_mean", & nPU_mean);
    mytree->SetBranchStatus("puWeight",1);
    mytree->SetBranchAddress("puWeight", & puWeight);
    mytree->SetBranchStatus("puWeight_Up",1);
    mytree->SetBranchAddress("puWeight_Up", & puWeight_Up);
    mytree->SetBranchStatus("puWeight_Dn",1);
    mytree->SetBranchAddress("puWeight_Dn", & puWeight_Dn);
    mytree->SetBranchStatus("L1PFWeight",1);
    mytree->SetBranchAddress("L1PFWeight", & L1PFWeight);
    mytree->SetBranchStatus("lep1_pt",1);
    mytree->SetBranchAddress("lep1_pt", & lep1_pt);
    mytree->SetBranchStatus("lep1_eta",1);
    mytree->SetBranchAddress("lep1_eta", & lep1_eta);
    mytree->SetBranchStatus("lep1_phi",1);
    mytree->SetBranchAddress("lep1_phi", & lep1_phi);
    mytree->SetBranchStatus("lep1_m",1);
    mytree->SetBranchAddress("lep1_m", & lep1_m);
    mytree->SetBranchStatus("lep1_q",1);
    mytree->SetBranchAddress("lep1_q", & lep1_q);
    mytree->SetBranchStatus("lep1_iso",1);
    mytree->SetBranchAddress("lep1_iso", & lep1_iso);
    mytree->SetBranchStatus("lep1_idEffWeight",1);
    mytree->SetBranchAddress("lep1_idEffWeight", & lep1_idEffWeight);
    mytree->SetBranchStatus("lep1_pt_scaleUp",1);
    mytree->SetBranchAddress("lep1_pt_scaleUp", & lep1_pt_scaleUp);
    mytree->SetBranchStatus("lep1_pt_scaleDn",1);
    mytree->SetBranchAddress("lep1_pt_scaleDn", & lep1_pt_scaleDn);
    mytree->SetBranchStatus("lep2_pt",1);
    mytree->SetBranchAddress("lep2_pt", & lep2_pt);
    mytree->SetBranchStatus("lep2_eta",1);
    mytree->SetBranchAddress("lep2_eta", & lep2_eta);
    mytree->SetBranchStatus("lep2_phi",1);
    mytree->SetBranchAddress("lep2_phi", & lep2_phi);
    mytree->SetBranchStatus("lep2_m",1);
    mytree->SetBranchAddress("lep2_m", & lep2_m);
    mytree->SetBranchStatus("lep2_q",1);
    mytree->SetBranchAddress("lep2_q", & lep2_q);
    mytree->SetBranchStatus("lep2_iso",1);
    mytree->SetBranchAddress("lep2_iso", & lep2_iso);
    mytree->SetBranchStatus("lep2_idEffWeight",1);
    mytree->SetBranchAddress("lep2_idEffWeight", & lep2_idEffWeight);
    mytree->SetBranchStatus("lep2_pt_scaleUp",1);
    mytree->SetBranchAddress("lep2_pt_scaleUp", & lep2_pt_scaleUp);
    mytree->SetBranchStatus("lep2_pt_scaleDn",1);
    mytree->SetBranchAddress("lep2_pt_scaleDn", & lep2_pt_scaleDn);
    mytree->SetBranchStatus("dilep_m",1);
    mytree->SetBranchAddress("dilep_m", & dilep_m);
    mytree->SetBranchStatus("dilep_pt",1);
    mytree->SetBranchAddress("dilep_pt", & dilep_pt);
    mytree->SetBranchStatus("dilep_eta",1);
    mytree->SetBranchAddress("dilep_eta", & dilep_eta);
    mytree->SetBranchStatus("dilep_phi",1);
    mytree->SetBranchAddress("dilep_phi", & dilep_phi);
    mytree->SetBranchStatus("dilep_m_ScaleUp",1);
    mytree->SetBranchAddress("dilep_m_ScaleUp", & dilep_m_ScaleUp);
    mytree->SetBranchStatus("dilep_m_ScaleDn",1);
    mytree->SetBranchAddress("dilep_m_ScaleDn", & dilep_m_ScaleDn);
    mytree->SetBranchStatus("dilep__pt_ScaleUp",1);
    mytree->SetBranchAddress("dilep__pt_ScaleUp", & dilep__pt_ScaleUp);
    mytree->SetBranchStatus("dilep_pt_ScaleDn",1);
    mytree->SetBranchAddress("dilep_pt_ScaleDn", & dilep_pt_ScaleDn);
    mytree->SetBranchStatus("MET",1);
    mytree->SetBranchAddress("MET", & MET);
    mytree->SetBranchStatus("MET_phi",1);
    mytree->SetBranchAddress("MET_phi", & MET_phi);
    mytree->SetBranchStatus("MET_2017raw",1);
    mytree->SetBranchAddress("MET_2017raw", & MET_2017raw);
    mytree->SetBranchStatus("MET_ScaleUp",1);
    mytree->SetBranchAddress("MET_ScaleUp", & MET_ScaleUp);
    mytree->SetBranchStatus("MET_Scale_Dn",1);
    mytree->SetBranchAddress("MET_Scale_Dn", & MET_Scale_Dn);
    mytree->SetBranchStatus("neu_pz_type0=",1);
    mytree->SetBranchAddress("neu_pz_type0=", & neu_pz_type0=);
    mytree->SetBranchStatus("neu_pz_type0_scaleUp",1);
    mytree->SetBranchAddress("neu_pz_type0_scaleUp", & neu_pz_type0_scaleUp);
    mytree->SetBranchStatus("neu_pz_type0_scaleDn",1);
    mytree->SetBranchAddress("neu_pz_type0_scaleDn", & neu_pz_type0_scaleDn);
    mytree->SetBranchStatus("vbf1_AK4_pt",1);
    mytree->SetBranchAddress("vbf1_AK4_pt", & vbf1_AK4_pt);
    mytree->SetBranchStatus("vbf1_AK4_eta",1);
    mytree->SetBranchAddress("vbf1_AK4_eta", & vbf1_AK4_eta);
    mytree->SetBranchStatus("vbf1_AK4_phi",1);
    mytree->SetBranchAddress("vbf1_AK4_phi", & vbf1_AK4_phi);
    mytree->SetBranchStatus("vbf1_AK4_m",1);
    mytree->SetBranchAddress("vbf1_AK4_m", & vbf1_AK4_m);
    mytree->SetBranchStatus("vbf1_AK4_gqid",1);
    mytree->SetBranchAddress("vbf1_AK4_gqid", & vbf1_AK4_gqid);
    mytree->SetBranchStatus("vbf1_AK4_axis2",1);
    mytree->SetBranchAddress("vbf1_AK4_axis2", & vbf1_AK4_axis2);
    mytree->SetBranchStatus("vbf1_AK4_ptD",1);
    mytree->SetBranchAddress("vbf1_AK4_ptD", & vbf1_AK4_ptD);
    mytree->SetBranchStatus("vbf1_AK4_pt_scaleUp",1);
    mytree->SetBranchAddress("vbf1_AK4_pt_scaleUp", & vbf1_AK4_pt_scaleUp);
    mytree->SetBranchStatus("vbf1_AK4_pt_scaleDn",1);
    mytree->SetBranchAddress("vbf1_AK4_pt_scaleDn", & vbf1_AK4_pt_scaleDn);
    mytree->SetBranchStatus("vbf1_AK4_m_scaleUp",1);
    mytree->SetBranchAddress("vbf1_AK4_m_scaleUp", & vbf1_AK4_m_scaleUp);
    mytree->SetBranchStatus("vbf1_AK4_m_scaleDn",1);
    mytree->SetBranchAddress("vbf1_AK4_m_scaleDn", & vbf1_AK4_m_scaleDn);
    mytree->SetBranchStatus("vbf2_AK4_pt",1);
    mytree->SetBranchAddress("vbf2_AK4_pt", & vbf2_AK4_pt);
    mytree->SetBranchStatus("vbf2_AK4_eta",1);
    mytree->SetBranchAddress("vbf2_AK4_eta", & vbf2_AK4_eta);
    mytree->SetBranchStatus("vbf2_AK4_phi",1);
    mytree->SetBranchAddress("vbf2_AK4_phi", & vbf2_AK4_phi);
    mytree->SetBranchStatus("vbf2_AK4_m",1);
    mytree->SetBranchAddress("vbf2_AK4_m", & vbf2_AK4_m);
    mytree->SetBranchStatus("vbf2_AK4_gqid",1);
    mytree->SetBranchAddress("vbf2_AK4_gqid", & vbf2_AK4_gqid);
    mytree->SetBranchStatus("vbf2_AK4_axis2",1);
    mytree->SetBranchAddress("vbf2_AK4_axis2", & vbf2_AK4_axis2);
    mytree->SetBranchStatus("vbf2_AK4_ptD",1);
    mytree->SetBranchAddress("vbf2_AK4_ptD", & vbf2_AK4_ptD);
    mytree->SetBranchStatus("vbf2_AK4_pt_scaleUp",1);
    mytree->SetBranchAddress("vbf2_AK4_pt_scaleUp", & vbf2_AK4_pt_scaleUp);
    mytree->SetBranchStatus("vbf2_AK4_pt_scaleDn",1);
    mytree->SetBranchAddress("vbf2_AK4_pt_scaleDn", & vbf2_AK4_pt_scaleDn);
    mytree->SetBranchStatus("vbf2_AK4_m_scaleUp",1);
    mytree->SetBranchAddress("vbf2_AK4_m_scaleUp", & vbf2_AK4_m_scaleUp);
    mytree->SetBranchStatus("vbf2_AK4_m_scaleDn",1);
    mytree->SetBranchAddress("vbf2_AK4_m_scaleDn", & vbf2_AK4_m_scaleDn);
    mytree->SetBranchStatus("vbf_pt",1);
    mytree->SetBranchAddress("vbf_pt", & vbf_pt);
    mytree->SetBranchStatus("vbf_eta",1);
    mytree->SetBranchAddress("vbf_eta", & vbf_eta);
    mytree->SetBranchStatus("vbf_phi",1);
    mytree->SetBranchAddress("vbf_phi", & vbf_phi);
    mytree->SetBranchStatus("vbf_m",1);
    mytree->SetBranchAddress("vbf_m", & vbf_m);
    mytree->SetBranchStatus("vbf_pt_scaleUp",1);
    mytree->SetBranchAddress("vbf_pt_scaleUp", & vbf_pt_scaleUp);
    mytree->SetBranchStatus("vbf_pt_scaleDn",1);
    mytree->SetBranchAddress("vbf_pt_scaleDn", & vbf_pt_scaleDn);
    mytree->SetBranchStatus("vbf_m_scaleUp",1);
    mytree->SetBranchAddress("vbf_m_scaleUp", & vbf_m_scaleUp);
    mytree->SetBranchStatus("vbf_m_scaleDn",1);
    mytree->SetBranchAddress("vbf_m_scaleDn", & vbf_m_scaleDn);
    mytree->SetBranchStatus("bos_PuppiAK8_m_sd0",1);
    mytree->SetBranchAddress("bos_PuppiAK8_m_sd0", & bos_PuppiAK8_m_sd0);
    mytree->SetBranchStatus("bos_PuppiAK8_m_sd0_corr",1);
    mytree->SetBranchAddress("bos_PuppiAK8_m_sd0_corr", & bos_PuppiAK8_m_sd0_corr);
    mytree->SetBranchStatus("bos_PuppiAK8_pt",1);
    mytree->SetBranchAddress("bos_PuppiAK8_pt", & bos_PuppiAK8_pt);
    mytree->SetBranchStatus("bos_PuppiAK8_eta",1);
    mytree->SetBranchAddress("bos_PuppiAK8_eta", & bos_PuppiAK8_eta);
    mytree->SetBranchStatus("bos_PuppiAK8_phi",1);
    mytree->SetBranchAddress("bos_PuppiAK8_phi", & bos_PuppiAK8_phi);
    mytree->SetBranchStatus("bos_PuppiAK8_tau2tau1",1);
    mytree->SetBranchAddress("bos_PuppiAK8_tau2tau1", & bos_PuppiAK8_tau2tau1);
    mytree->SetBranchStatus("bos_PuppiAK8_m_sd0_corr_ScaleUp",1);
    mytree->SetBranchAddress("bos_PuppiAK8_m_sd0_corr_ScaleUp", & bos_PuppiAK8_m_sd0_corr_ScaleUp);
    mytree->SetBranchStatus("bos_PuppiAK8_m_sd0_corr_scaleDn",1);
    mytree->SetBranchAddress("bos_PuppiAK8_m_sd0_corr_scaleDn", & bos_PuppiAK8_m_sd0_corr_scaleDn);
    mytree->SetBranchStatus("bos_PuppiAK8_pt_scaleUp",1);
    mytree->SetBranchAddress("bos_PuppiAK8_pt_scaleUp", & bos_PuppiAK8_pt_scaleUp);
    mytree->SetBranchStatus("bos_PuppiAK8_pt_scaleDn",1);
    mytree->SetBranchAddress("bos_PuppiAK8_pt_scaleDn", & bos_PuppiAK8_pt_scaleDn);
    mytree->SetBranchStatus("bos_PuppiAK8_e2_sdb1",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e2_sdb1", & bos_PuppiAK8_e2_sdb1);
    mytree->SetBranchStatus("bos_PuppiAK8_e3_sdb1",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e3_sdb1", & bos_PuppiAK8_e3_sdb1);
    mytree->SetBranchStatus("bos_PuppiAK8_e3_v1_sdb1",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e3_v1_sdb1", & bos_PuppiAK8_e3_v1_sdb1);
    mytree->SetBranchStatus("bos_PuppiAK8_e3_v2_sdb1",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e3_v2_sdb1", & bos_PuppiAK8_e3_v2_sdb1);
    mytree->SetBranchStatus("bos_PuppiAK8_e4_v1_sdb1",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e4_v1_sdb1", & bos_PuppiAK8_e4_v1_sdb1);
    mytree->SetBranchStatus("bos_PuppiAK8_e4_v2_sdb1",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e4_v2_sdb1", & bos_PuppiAK8_e4_v2_sdb1);
    mytree->SetBranchStatus("bos_PuppiAK8_e2_sdb2",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e2_sdb2", & bos_PuppiAK8_e2_sdb2);
    mytree->SetBranchStatus("bos_PuppiAK8_e3_sdb2",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e3_sdb2", & bos_PuppiAK8_e3_sdb2);
    mytree->SetBranchStatus("bos_PuppiAK8_e3_v1_sdb2",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e3_v1_sdb2", & bos_PuppiAK8_e3_v1_sdb2);
    mytree->SetBranchStatus("bos_PuppiAK8_e3_v2_sdb2",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e3_v2_sdb2", & bos_PuppiAK8_e3_v2_sdb2);
    mytree->SetBranchStatus("bos_PuppiAK8_e4_v1_sdb2",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e4_v1_sdb2", & bos_PuppiAK8_e4_v1_sdb2);
    mytree->SetBranchStatus("bos_PuppiAK8_e4_v2_sdb2",1);
    mytree->SetBranchAddress("bos_PuppiAK8_e4_v2_sdb2", & bos_PuppiAK8_e4_v2_sdb2);
    mytree->SetBranchStatus("bos_j1_AK4_pt",1);
    mytree->SetBranchAddress("bos_j1_AK4_pt", & bos_j1_AK4_pt);
    mytree->SetBranchStatus("bos_j1_AK4_eta",1);
    mytree->SetBranchAddress("bos_j1_AK4_eta", & bos_j1_AK4_eta);
    mytree->SetBranchStatus("bos_j1_AK4_phi",1);
    mytree->SetBranchAddress("bos_j1_AK4_phi", & bos_j1_AK4_phi);
    mytree->SetBranchStatus("bos_j1_AK4_m",1);
    mytree->SetBranchAddress("bos_j1_AK4_m", & bos_j1_AK4_m);
    mytree->SetBranchStatus("bos_j1_AK4_pt_scaleUp",1);
    mytree->SetBranchAddress("bos_j1_AK4_pt_scaleUp", & bos_j1_AK4_pt_scaleUp);
    mytree->SetBranchStatus("bos_j1_AK4_pt_scaleDn",1);
    mytree->SetBranchAddress("bos_j1_AK4_pt_scaleDn", & bos_j1_AK4_pt_scaleDn);
    mytree->SetBranchStatus("bos_j1_AK4_m_scaleUp",1);
    mytree->SetBranchAddress("bos_j1_AK4_m_scaleUp", & bos_j1_AK4_m_scaleUp);
    mytree->SetBranchStatus("bos_j1_AK4_m_scaleDn",1);
    mytree->SetBranchAddress("bos_j1_AK4_m_scaleDn", & bos_j1_AK4_m_scaleDn);
    mytree->SetBranchStatus("bos_j2_AK4_pt",1);
    mytree->SetBranchAddress("bos_j2_AK4_pt", & bos_j2_AK4_pt);
    mytree->SetBranchStatus("bos_j2_AK4_eta",1);
    mytree->SetBranchAddress("bos_j2_AK4_eta", & bos_j2_AK4_eta);
    mytree->SetBranchStatus("bos_j2_AK4_phi",1);
    mytree->SetBranchAddress("bos_j2_AK4_phi", & bos_j2_AK4_phi);
    mytree->SetBranchStatus("bos_j2_AK4_m",1);
    mytree->SetBranchAddress("bos_j2_AK4_m", & bos_j2_AK4_m);
    mytree->SetBranchStatus("bos_j2_AK4_pt_scaleUp",1);
    mytree->SetBranchAddress("bos_j2_AK4_pt_scaleUp", & bos_j2_AK4_pt_scaleUp);
    mytree->SetBranchStatus("bos_j2_AK4_pt_scaleDn",1);
    mytree->SetBranchAddress("bos_j2_AK4_pt_scaleDn", & bos_j2_AK4_pt_scaleDn);
    mytree->SetBranchStatus("bos_j2_AK4_m_scaleUp",1);
    mytree->SetBranchAddress("bos_j2_AK4_m_scaleUp", & bos_j2_AK4_m_scaleUp);
    mytree->SetBranchStatus("bos_j2_AK4_m_scaleDn",1);
    mytree->SetBranchAddress("bos_j2_AK4_m_scaleDn", & bos_j2_AK4_m_scaleDn);
    mytree->SetBranchStatus("bos_AK4AK4_pt",1);
    mytree->SetBranchAddress("bos_AK4AK4_pt", & bos_AK4AK4_pt);
    mytree->SetBranchStatus("bos_AK4AK4_eta",1);
    mytree->SetBranchAddress("bos_AK4AK4_eta", & bos_AK4AK4_eta);
    mytree->SetBranchStatus("bos_AK4AK4_phi",1);
    mytree->SetBranchAddress("bos_AK4AK4_phi", & bos_AK4AK4_phi);
    mytree->SetBranchStatus("bos_AK4AK4_m",1);
    mytree->SetBranchAddress("bos_AK4AK4_m", & bos_AK4AK4_m);
    mytree->SetBranchStatus("bos_AK4AK4_pt_scaleUp",1);
    mytree->SetBranchAddress("bos_AK4AK4_pt_scaleUp", & bos_AK4AK4_pt_scaleUp);
    mytree->SetBranchStatus("bos_AK4AK4_pt_scaleDn",1);
    mytree->SetBranchAddress("bos_AK4AK4_pt_scaleDn", & bos_AK4AK4_pt_scaleDn);
    mytree->SetBranchStatus("bos_AK4AK4_m_scaleUp",1);
    mytree->SetBranchAddress("bos_AK4AK4_m_scaleUp", & bos_AK4AK4_m_scaleUp);
    mytree->SetBranchStatus("bos_AK4AK4_m_scaleDn",1);
    mytree->SetBranchAddress("bos_AK4AK4_m_scaleDn", & bos_AK4AK4_m_scaleDn);
    mytree->SetBranchStatus("dibos_m",1);
    mytree->SetBranchAddress("dibos_m", & dibos_m);
    mytree->SetBranchStatus("dibos_pt",1);
    mytree->SetBranchAddress("dibos_pt", & dibos_pt);
    mytree->SetBranchStatus("dibos_eta",1);
    mytree->SetBranchAddress("dibos_eta", & dibos_eta);
    mytree->SetBranchStatus("dibos_phi",1);
    mytree->SetBranchAddress("dibos_phi", & dibos_phi);
    mytree->SetBranchStatus("dibos_m_scaleUp",1);
    mytree->SetBranchAddress("dibos_m_scaleUp", & dibos_m_scaleUp);
    mytree->SetBranchStatus("dibos_m_scaleDn",1);
    mytree->SetBranchAddress("dibos_m_scaleDn", & dibos_m_scaleDn);
    mytree->SetBranchStatus("dibos_pt_scaleUp",1);
    mytree->SetBranchAddress("dibos_pt_scaleUp", & dibos_pt_scaleUp);
    mytree->SetBranchStatus("dibos_pt_scaleDn",1);
    mytree->SetBranchAddress("dibos_pt_scaleDn", & dibos_pt_scaleDn);
    mytree->SetBranchStatus("bosCent",1);
    mytree->SetBranchAddress("bosCent", & bosCent);
    mytree->SetBranchStatus("zeppLep",1);
    mytree->SetBranchAddress("zeppLep", & zeppLep);
    mytree->SetBranchStatus("zeppHad=",1);
    mytree->SetBranchAddress("zeppHad=", & zeppHad=);
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

